#=================================================
# Description: Build Android HAL and dhd packages using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
#=================================================

name: Build SailfishOS dhd

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-16.04

    env:
      DEVICE: cosmocom
      VENDOR: planet
      ANDROID_ROOT: /home/runner/work/hadk_16.0/
      SAILFISH_SKD_VERSION: 3.3.0.14

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc \
        bison build-essential curl flex g++-multilib \
        gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev \
        lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool \
        libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc yasm zip zlib1g-dev git


    - name: Download repo bin file
      run: |
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "CI user"
        git config --global user.email "doesnotexist@example.com"

    - name: Downloading source code
      run: |
        source hadk.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u git://github.com/mer-hybris/android.git -b hybris-16.0 --depth=1
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Clone device spec source
      run: |
        source hadk.env
        git clone https://github.com/Sailfish-on-Cosmo-Communicator/android_device_planet_cosmocom.git $ANDROID_ROOT/device/planet/cosmocom -b hybris-16.0 --depth=1
        git clone https://github.com/gemian/cosmo-linux-kernel-4.4.git $ANDROID_ROOT/kernel/planet/mt6771 -b ubports --depth=1
        rm -rf $ANDROID_ROOT/hybris/hybris-boot
        git clone https://github.com/Sailfish-on-Cosmo-Communicator/hybris-boot.git $ANDROID_ROOT/hybris/hybris-boot -b cosmocom
        git clone --recurse-submodules https://github.com/Sailfish-on-Cosmo-Communicator/droid-hal-cosmocom.git $ANDROID_ROOT/rpm
        git clone --recurse-submodules https://github.com/Sailfish-on-Cosmo-Communicator/droid-config-cosmocom.git $ANDROID_ROOT/hybris/droid-configs
        git clone --recurse-submodules https://github.com/Sailfish-on-Cosmo-Communicator/droid-hal-version-cosmocom.git $ANDROID_ROOT/hybris/droid-hal-version-cosmocom
        rm -rf $ANDROID_ROOT/external/droidmedia
        git clone https://github.com/sailfishos/droidmedia.git $ANDROID_ROOT/external/droidmedia

    - name: Build HAL
      run: |
        chmod +x build-hal.sh
        bash build-hal.sh
      shell: bash

    - name: Build dhd in container
      run: |
        echo "clean more folders"
        rm -rf $ANDROID_ROOT/prebuilts $ANDROID_ROOT/external/chromium* $ANDROID_ROOT/tools/external/gradle $ANDROID_ROOT/packages
        rm -rf $ANDROID_ROOT/out/build-lineage_cosmocom.ninja || true
        rm -rf $ANDROID_ROOT/out/soong
        chmod +x build-rpm.sh
        sudo docker images|grep -v REPOSITORY|awk '{print $3}'|xargs docker rmi
        sudo docker pull coderus/sailfishos-platform-sdk:$SAILFISH_SKD_VERSION
        sudo docker run -v /home/runner/work:/home/nemo/work coderus/sailfishos-platform-sdk:$SAILFISH_SKD_VERSION /bin/sh /home/nemo/work/ci/ci/build-rpm.sh
      shell: bash

    - name: Check free disk
      if: failure()
      run: |
        df -h
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: hybris-boot.img
        path: ${{env.ANDROID_ROOT}}/out/target/product/${{env.DEVICE}}/hybris-boot.img

    - name : Upload droid-local-repo
      uses: actions/upload-artifact@master
      with:
        name: droid-local-repo
        path: ${{env.ANDROID_ROOT}}/droid-local-repo
